set(CMAKE_BUILD_TYPE Debug CACHE INTERNAL "")
set(SCORE_STATIC_PLUGINS True CACHE INTERNAL "")
#set(CMAKE_CXX_COMPILER /usr/bin/clazy)
set(SCORE_COTIRE False CACHE INTERNAL "")
set(DEPLOYMENT_BUILD False)
set(SCORE_COVERAGE False)

include(default-plugins)
