set(CMAKE_C_FLAGS "-Og -g ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "-Og -g ${CMAKE_CXX_FLAGS}")
# set(CMAKE_BUILD_TYPE Debug CACHE INTERNAL "")
set(SCORE_PCH True)
set(SCORE_STATIC_PLUGINS 0 CACHE INTERNAL "")
# set(CMAKE_CXX_COMPILER /usr/bin/clazy)

# set(SCORE_PCH True CACHE INTERNAL "")
set(DEPLOYMENT_BUILD False)
set(SCORE_COVERAGE False)
set(SCORE_AUDIO_PLUGINS True CACHE INTERNAL "")

include(default-plugins)
