// =============================================================================
// FOUR-WAY INDIRECT DRAW BENCHMARK over one compute-generated scene.
//
// Registration: score_add_gfx_test(indirect_draw_bench GfxIndirectDrawBench.cpp)
//
// Same scene, geometry and oracle on all four paths (corpus/
// syn-indirect-bench.cs: 4096 command slots, one 2x2 px quad each on a 256x256
// target, all 49152 vertices regenerated by compute every frame, GPU count
// alive=3072, dead slots poisoned):
//
//   count  — drawIndirectCount (GPU count buffer)         [no switches]
//   mdi    — one full-capacity multi-draw indirect        [NO_GPU_INDIRECT_COUNT]
//   loop   — 4096 drawCount=1 indirect draws              [+ NO_GPU_INDIRECT_MULTI]
//   cpu    — CPU loop over commands read back each frame  [NO_GPU_INDIRECT]
//            (this path's cost INCLUDES the per-frame readback + rhi->finish()
//             stall that the engine's fallback performs; that is its honest
//             price, not an artifact)
//
// Each session REQUIREs the caps line matching the path it claims (positive
// control: a benchmark of a silently-fallen-back path is worse than none) and
// spot-checks the oracle so a path that draws garbage cannot post a number.
// Metal: the count path is DECLINED by drawIndirectCountUsable(), reported as
// declined, not zero.
//
// Measurement: CPU wall time of one whole-graph frame (GfxPipeline::render(1)
// — compute passes + draw + offscreen present) on the render path,
// std::chrono::steady_clock, 8 warmup frames then 48 timed frames; median /
// p10 / p90 reported in "BENCH ..." stdout lines. Build type and GPU are
// reported by the harness environment, not assumed here.
// =============================================================================
#include "IsfTestCommon.hpp"

#include <QtCore/qlogging.h>

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <regex>
#include <string>
#include <vector>

namespace
{
using namespace score::test::gfx;
using namespace score::test::gfx::isf;

constexpr int kSize = 256;
constexpr int kSlots = 4096;
constexpr int kAlive = 3072;
constexpr int kAlivePort = 0;
constexpr int kPoisonPort = 1;
constexpr int kWarmup = 8;
constexpr int kTimed = 48;
constexpr int kTol = 2;

struct LogCapture
{
  static inline std::string text;
  static inline QtMessageHandler prev = nullptr;
  static void handler(QtMsgType t, const QMessageLogContext& c, const QString& m)
  {
    text += m.toStdString();
    text += '\n';
    if(prev)
      prev(t, c, m);
  }
  LogCapture()
  {
    text.clear();
    prev = qInstallMessageHandler(&handler);
  }
  ~LogCapture()
  {
    qInstallMessageHandler(prev);
    prev = nullptr;
  }
};

struct BenchResult
{
  bool skipped = false;
  std::string skip_reason;
  std::string error;
  std::string backend;
  bool capsParsed = false;
  int capsDrawIndirect = -1, capsMulti = -1, capsCount = -1, capsDispatch = -1;
  std::string dispatchLog;
  std::vector<double> frame_ms;
  ReadbackImage shot;
};

const char* const kSwitches[] = {
    "SCORE_GFX_NO_GPU_INDIRECT",
    "SCORE_GFX_NO_GPU_INDIRECT_COUNT",
    "SCORE_GFX_NO_GPU_INDIRECT_MULTI",
    "SCORE_GFX_NO_GPU_DISPATCH_INDIRECT",
};

BenchResult run_bench(
    score::gfx::GraphicsApi be, std::initializer_list<const char*> switches)
{
  BenchResult r;
  r.backend = backend_name(be);
  for(const char* s : kSwitches)
    qunsetenv(s);
  for(const char* s : switches)
    qputenv(s, "1");

  score::test::run_in_gui_app([&](const score::GUIApplicationContext&) {
    LogCapture capture;

    GfxPipeline p;
    const int csf = p.addIsf(corpus("syn-indirect-bench.cs"));
    const int raster
        = p.addRaster(corpus("syn-vertex-color.vs"), corpus("syn-vertex-color.fs"));
    if(csf < 0 || raster < 0)
    {
      r.error = "node build failed: " + p.error();
      return;
    }
    auto* gout = p.geometryOut(csf, 0);
    auto* gin = p.geometryIn(raster, 0);
    if(!gout || !gin)
    {
      r.error = "geometry ports missing";
      return;
    }
    p.wire(gout, gin);
    const int sink = p.addSink({kSize, kSize});
    p.wire(p.imageOut(raster, 0), p.sinkInput(sink));

    if(!p.create(be))
    {
      r.backend = p.backend();
      r.skipped = p.skipped();
      r.skip_reason = p.skipReason();
      r.error = p.error();
      return;
    }
    r.backend = p.backend();

    setControl(*p.isf(csf), kAlivePort, ossia::value{kAlive});
    setControl(*p.isf(csf), kPoisonPort, ossia::value{1});

    p.render(kWarmup);

    r.frame_ms.reserve(kTimed);
    for(int i = 0; i < kTimed; ++i)
    {
      const auto t0 = std::chrono::steady_clock::now();
      p.render(1);
      const auto t1 = std::chrono::steady_clock::now();
      r.frame_ms.push_back(
          std::chrono::duration<double, std::milli>(t1 - t0).count());
    }
    r.shot = p.readback(sink);

    static const std::regex caps_re(
        "RHI indirect caps: drawIndirect=([01]) multi=([01]) count=([01]) "
        "dispatchIndirect=([01])");
    for(std::sregex_iterator
            it(capture.text.begin(), capture.text.end(), caps_re),
        end;
        it != end; ++it)
    {
      r.capsParsed = true;
      r.capsDrawIndirect = (*it)[1] == "1";
      r.capsMulti = (*it)[2] == "1";
      r.capsCount = (*it)[3] == "1";
      r.capsDispatch = (*it)[4] == "1";
    }
    if(capture.text.find("CSF indirect dispatch: gpu") != std::string::npos)
      r.dispatchLog = "gpu";
    else if(
        capture.text.find("CSF indirect dispatch: cpu-fallback")
        != std::string::npos)
      r.dispatchLog = "cpu-fallback";
  });

  for(const char* s : kSwitches)
    qunsetenv(s);
  return r;
}

/// Cell c: sample the top-left interior pixel of its 2x2 quad.
/// NDC row cy occupies screen rows [253 - 4*cy, 255 - 4*cy).
std::array<int, 2> cell_probe(int cell)
{
  const int cx = cell % 64, cy = cell / 64;
  return {4 * cx + 1, 253 - 4 * cy};
}

void spot_check(const ReadbackImage& img, bool poisonVisible)
{
  REQUIRE(img.valid());
  REQUIRE(img.width == kSize);
  REQUIRE(img.height == kSize);
  const std::array<uint8_t, 4> red{255, 0, 0, 255};
  const std::array<uint8_t, 4> blue{0, 0, 255, 255};
  for(int c : {0, 1, kAlive / 2, kAlive - 1})
  {
    const auto pr = cell_probe(c);
    const auto px = img.at(pr[0], pr[1]);
    INFO("lit cell " << c << " px=(" << int(px[0]) << "," << int(px[1]) << ","
                     << int(px[2]) << ")");
    CHECK(near(px, red, kTol));
  }
  for(int c : {kAlive, kAlive + 1, kSlots - 1})
  {
    const auto pr = cell_probe(c);
    const auto px = img.at(pr[0], pr[1]);
    INFO("dead cell " << c << " px=(" << int(px[0]) << "," << int(px[1]) << ","
                      << int(px[2]) << ")");
    if(poisonVisible)
      CHECK(near(px, blue, kTol));
    else
      CHECK(int(px[2]) < 255 - 4 * kTol);
  }
}

double percentile(std::vector<double> v, double p)
{
  std::sort(v.begin(), v.end());
  const size_t i = std::min(v.size() - 1, size_t(p * (v.size() - 1) + 0.5));
  return v[i];
}

void report(const BenchResult& r, const char* path, bool poisonVisible)
{
  spot_check(r.shot, poisonVisible);
  std::fprintf(
      stderr,
      "BENCH backend=%s path=%s slots=%d alive=%d frames=%d "
      "median_ms=%.3f p10_ms=%.3f p90_ms=%.3f caps=%d%d%d%d dispatch=%s\n",
      r.backend.c_str(), path, kSlots, kAlive, kTimed,
      percentile(r.frame_ms, 0.5), percentile(r.frame_ms, 0.10),
      percentile(r.frame_ms, 0.90), r.capsDrawIndirect, r.capsMulti,
      r.capsCount, r.capsDispatch, r.dispatchLog.c_str());
}
} // namespace

TEST_CASE(
    "four-way indirect draw benchmark over a compute-generated scene",
    "[gfx][l3][raster][csf][indirect][bench]")
{
  const auto backend = GENERATE(from_range(platform_backends()));

  // Path d: drawIndirectCount.
  const BenchResult count = run_bench(backend, {});
  if(count.skipped)
    SKIP(count.backend + ": " + count.skip_reason);
  if(const char* why = compute_shader_skip_reason(backend))
    SKIP(why);
  INFO("backend=" << count.backend);
  REQUIRE(count.error.empty());
  REQUIRE(count.capsParsed);

  const bool metal = backend == score::gfx::Metal;
  const bool countRung = count.capsCount == 1 && !metal;
  if(count.capsDispatch == 1)
    REQUIRE(count.dispatchLog == "gpu");

  if(countRung)
  {
    report(count, "count", /*poisonVisible=*/false);
  }
  else if(metal && count.capsCount == 1)
  {
    std::fprintf(
        stderr,
        "BENCH backend=%s path=count DECLINED (drawIndirectCountUsable: "
        "Metal prerequisites not plumbed) — capacity rung measured under "
        "path=mdi instead\n",
        count.backend.c_str());
    // The no-switch session ran the capacity rung; its numbers belong to mdi.
  }
  else
  {
    std::fprintf(
        stderr, "BENCH backend=%s path=count UNAVAILABLE (caps count=%d)\n",
        count.backend.c_str(), count.capsCount);
  }

  // Path c: one full-capacity multi-draw.
  {
    const BenchResult r = run_bench(backend, {"SCORE_GFX_NO_GPU_INDIRECT_COUNT"});
    REQUIRE(r.error.empty());
    REQUIRE(r.capsParsed);
    REQUIRE(r.capsCount == 0);
    if(r.capsDrawIndirect == 1)
      report(r, "mdi", /*poisonVisible=*/true);
    else
      std::fprintf(
          stderr, "BENCH backend=%s path=mdi UNAVAILABLE (no drawIndirect)\n",
          r.backend.c_str());
  }

  // Path b: per-command indirect loop.
  {
    const BenchResult r = run_bench(
        backend,
        {"SCORE_GFX_NO_GPU_INDIRECT_COUNT", "SCORE_GFX_NO_GPU_INDIRECT_MULTI"});
    REQUIRE(r.error.empty());
    REQUIRE(r.capsParsed);
    REQUIRE(r.capsCount == 0);
    REQUIRE(r.capsMulti == 0);
    if(r.capsDrawIndirect == 1)
      report(r, "loop", /*poisonVisible=*/true);
    else
      std::fprintf(
          stderr, "BENCH backend=%s path=loop UNAVAILABLE (no drawIndirect)\n",
          r.backend.c_str());
  }

  // Path a: CPU loop (includes the engine's per-frame readback + finish).
  {
    const BenchResult r = run_bench(backend, {"SCORE_GFX_NO_GPU_INDIRECT"});
    REQUIRE(r.error.empty());
    REQUIRE(r.capsParsed);
    REQUIRE(r.capsDrawIndirect == 0);
    report(r, "cpu", /*poisonVisible=*/false);
  }
}
