#ifndef ISCORE_PREFIX_HEADER
#define ISCORE_PREFIX_HEADER
#pragma warning(push, 0) // MSVC
#pragma GCC system_header
#pragma clang system_header

#include <QSize>
#include <QComboBox>
#include <QAbstractItemModel>
#include <QMenu>
#include <QFormLayout>
#include <QGraphicsScene>
#include <QLayout>
#include <QPen>
#include <QPointer>
#include <QIODevice>
#include <QFlags>
#include <QMetaType>
#include <QPair>
#include <QAction>
#include <QLineEdit>
#include <QPushButton>
#include <QColor>
#include <QGridLayout>
#include <QLabel>
#include <QApplication>
#include <QPainter>
#include <QJsonArray>
#include <QMap>
#include <QBoxLayout>
#include <QRect>
#include <QGraphicsItem>
#include <QVector>
#include <QDataStream>
#include <QStringList>
#include <QVariant>
#include <QWidget>
#include <QtGlobal>
#include <QPoint>
#include <QDebug>
#include <QJsonValue>
#include <QJsonObject>
#include <QList>
#include <QByteArray>
#include <QObject>
#include <QString>

/*
#include <QAbstractItemModel>
#include <QAbstractTransition>
#include <QAction>
#include <QActionGroup>
#include <QApplication>
#include <QBoxLayout>
#include <QBrush>
#include <QBuffer>
#include <QByteArray>
#include <QCheckBox>
#include <QChildEvent>
#include <QClipboard>
#include <QCloseEvent>
#include <QColor>
#include <QColorDialog>
#include <QComboBox>
#include <QCompleter>
#include <QContextMenuEvent>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QCursor>
#include <QDataStream>
#include <QDebug>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QDockWidget>
#include <QDoubleSpinBox>
#include <QEvent>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFinalState>
#include <QFont>
#include <QFormLayout>
#include <QFrame>
#include <QGraphicsItem>
#include <QGraphicsLayout>
#include <QGraphicsObject>
#include <QGraphicsProxyWidget>
#include <QGraphicsScene>
#include <QGraphicsSceneContextMenuEvent>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsSvgItem>
#include <QGraphicsTextItem>
#include <QGraphicsView>
#include <QGridLayout>
#include <QHash>
#include <QHBoxLayout>
#include <QHeaderView>
#include <QIcon>
#include <QInputDialog>
#include <QIntValidator>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QKeyEvent>
#include <QKeyEventTransition>
#include <QLabel>
#include <QLayout>
#include <QLineEdit>
#include <QList>
#include <QListView>
#include <QListWidget>
#include <QListWidgetItem>
#include <QMainWindow>
#include <QMap>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QMetaObject>
#include <QMetaType>
#include <QMimeData>
#include <QModelIndex>
#include <QMouseEvent>
#include <QObject>
#include <QPainter>
#include <QPainterPath>
#include <QPair>
#include <QPen>
#include <QPlainTextEdit>
#include <QPointer>
#include <QPointF>
#include <QPushButton>
#include <QRadioButton>
#include <QRecentFilesMenu.h>
#include <QRectF>
#include <QResizeEvent>
#include <QSaveFile>
#include <QScrollArea>
#include <QSettings>
#include <QSignalTransition>
#include <QSize>
#include <QSlider>
#include <QSortFilterProxyModel>
#include <QSpinBox>
#include <QSplashScreen>
#include <QStack>
#include <QStackedLayout>
#include <QStackedWidget>
#include <QStandardItemModel>
#include <QStandardPaths>
#include <QState>
#include <QStateMachine>
#include <QString>
#include <QStringList>
#include <QStyle>
#include <QStyleFactory>
#include <QSurfaceFormat>
#include <QSvgGenerator>
#include <QSvgRenderer>
#include <QTableView>
#include <QTableWidgetItem>
#include <QTabWidget>
#include <QtCore/QByteArray>
#include <QtCore/QDebug>
#include <QtCore/QHash>
#include <QtCore/QList>
#include <QtCore/QObject>
#include <QTemporaryFile>
#include <QTextBlock>
#include <QTextEdit>
#include <QThread>
#include <QTime>
#include <QTimeEdit>
#include <QToolBar>
#include <QToolButton>
#include <QTreeView>
#include <QtWebSockets/QWebSocket>
#include <QtWebSockets/QWebSocketServer>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QInputDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QVBoxLayout>
#include <QValidator>
#include <QVariant>
#include <QVariantList>
#include <QVBoxLayout>
#include <QVector>
#include <QWheelEvent>
#include <QWidget>
*/
#include <algorithm>
#include <array>
//#include <chrono>
#include <cmath>
//#include <csignal>
#include <cstdint>
#include <exception>
#include <functional>
//#include <iostream>
#include <iterator>
#include <map>
#include <memory>
#include <numeric>
//#include <queue>
//#include <random>
#include <set>
//#include <sstream>
#include <stdexcept>
#include <string>
//#include <thread>
#include <tuple>
#include <typeinfo>
#include <utility>
#include <vector>

#include <eggs/variant.hpp>

#include <boost/multi_index/mem_fun.hpp>
#include <boost/multi_index_container.hpp>
#include <boost/multi_index/hashed_index.hpp>
#include <boost/multi_index/sequenced_index.hpp>
// Messes with boost.spirit #include <boost/multi_index/ordered_index.hpp>

#include <boost/multi_index/member.hpp>
#include <boost/iterator/indirect_iterator.hpp>
#include <boost/container/flat_map.hpp>
#include <boost/optional.hpp>
#include <boost/range/algorithm.hpp>

#include <iscore/serialization/DataStreamVisitor.hpp>
#include <iscore/serialization/JSONValueVisitor.hpp>
#include <iscore/serialization/JSONVisitor.hpp>

#include <iscore/command/AggregateCommand.hpp>

#include <iscore/tools/ModelPath.hpp>
#include <iscore/tools/IdentifiedObjectMap.hpp>

#include <iscore/tools/TreeNode.hpp>
#include <iscore/tools/VariantBasedNode.hpp>
#include <iscore/tools/TreePath.hpp>

#include <iscore/plugins/customfactory/FactoryFamily.hpp>
#include <iscore/plugins/customfactory/FactoryInterface.hpp>
#include <iscore/plugins/customfactory/FactoryMap.hpp>

#include <iscore/selection/Selection.hpp>
#include <iscore/selection/SelectionDispatcher.hpp>
#endif
