#pragma once
/*
 * @file CudaP2PBridge.h
 * @brief TRANSITIONAL COMPATIBILITY SHIM — do not add new uses.
 *
 * The CUDA driver-API interop layer was renamed CudaP2PBridge -> CudaInterop
 * ("P2P" was a misnomer: the layer also does VMM alloc, GL/Vulkan/D3D
 * external-memory import, semaphores, DtoD copies and dma-buf export).
 * This header aliases the old cuda_p2p_* / CudaP2P* / CUDA_P2P_* names to the
 * new cuda_interop_* / CudaInterop* / CUDA_INTEROP_* symbols so downstream
 * code that has not yet been repointed keeps building. It will be deleted
 * once all consumers include <Gfx/Graph/interop/CudaInterop.h> directly.
 */
#include <Gfx/Graph/interop/CudaInterop.h>

#define cuda_p2p_alloc_buffer cuda_interop_alloc_buffer
#define CUDA_P2P_API CUDA_INTEROP_API
#define cuda_p2p_available cuda_interop_available
#define CudaP2PContextHandle CudaInteropContextHandle
#define CudaP2PContext_t CudaInteropContext_t
#define cuda_p2p_copy_array_to_buffer cuda_interop_copy_array_to_buffer
#define cuda_p2p_copy_buffer_to_array cuda_interop_copy_buffer_to_array
#define cuda_p2p_copy_dtod cuda_interop_copy_dtod
#define cuda_p2p_copy_dtod_2d cuda_interop_copy_dtod_2d
#define cuda_p2p_download_buffer cuda_interop_download_buffer
#define CudaP2PError CudaInteropError
#define CUDA_P2P_ERROR_ALLOC_FAILED CUDA_INTEROP_ERROR_ALLOC_FAILED
#define CUDA_P2P_ERROR_COPY_FAILED CUDA_INTEROP_ERROR_COPY_FAILED
#define CUDA_P2P_ERROR_FORMAT_NOT_SUPPORTED CUDA_INTEROP_ERROR_FORMAT_NOT_SUPPORTED
#define CUDA_P2P_ERROR_INIT_FAILED CUDA_INTEROP_ERROR_INIT_FAILED
#define CUDA_P2P_ERROR_INTEROP_FAILED CUDA_INTEROP_ERROR_INTEROP_FAILED
#define CUDA_P2P_ERROR_INVALID_HANDLE CUDA_INTEROP_ERROR_INVALID_HANDLE
#define CUDA_P2P_ERROR_INVALID_PARAMETER CUDA_INTEROP_ERROR_INVALID_PARAMETER
#define CUDA_P2P_ERROR_NO_DEVICE CUDA_INTEROP_ERROR_NO_DEVICE
#define CUDA_P2P_ERROR_NOT_INITIALIZED CUDA_INTEROP_ERROR_NOT_INITIALIZED
#define CUDA_P2P_ERROR_SYNC_FAILED CUDA_INTEROP_ERROR_SYNC_FAILED
#define CUDA_P2P_ERROR_UNKNOWN CUDA_INTEROP_ERROR_UNKNOWN
#define CUDA_P2P_FORMAT_FLOAT CUDA_INTEROP_FORMAT_FLOAT
#define CUDA_P2P_FORMAT_HALF CUDA_INTEROP_FORMAT_HALF
#define CUDA_P2P_FORMAT_SIGNED_INT16 CUDA_INTEROP_FORMAT_SIGNED_INT16
#define CUDA_P2P_FORMAT_SIGNED_INT32 CUDA_INTEROP_FORMAT_SIGNED_INT32
#define CUDA_P2P_FORMAT_SIGNED_INT8 CUDA_INTEROP_FORMAT_SIGNED_INT8
#define CUDA_P2P_FORMAT_UNSIGNED_INT16 CUDA_INTEROP_FORMAT_UNSIGNED_INT16
#define CUDA_P2P_FORMAT_UNSIGNED_INT32 CUDA_INTEROP_FORMAT_UNSIGNED_INT32
#define CUDA_P2P_FORMAT_UNSIGNED_INT8 CUDA_INTEROP_FORMAT_UNSIGNED_INT8
#define cuda_p2p_free_buffer cuda_interop_free_buffer
#define cuda_p2p_get_error_string cuda_interop_get_error_string
#define cuda_p2p_gl_write_buffer cuda_interop_gl_write_buffer
#define cuda_p2p_gl_write_image cuda_interop_gl_write_image
#define CudaP2PImageDesc CudaInteropImageDesc
#define CudaP2PImageFormat CudaInteropImageFormat
#define CudaP2PImageHandle CudaInteropImageHandle
#define CudaP2PImage_t CudaInteropImage_t
#define cuda_p2p_import_d3d11_buffer cuda_interop_import_d3d11_buffer
#define cuda_p2p_import_d3d12_buffer cuda_interop_import_d3d12_buffer
#define cuda_p2p_import_d3d12_fence cuda_interop_import_d3d12_fence
#define cuda_p2p_import_gl_buffer cuda_interop_import_gl_buffer
#define cuda_p2p_import_vulkan_buffer cuda_interop_import_vulkan_buffer
#define cuda_p2p_import_vulkan_image cuda_interop_import_vulkan_image
#define cuda_p2p_import_vulkan_semaphore cuda_interop_import_vulkan_semaphore
#define cuda_p2p_import_vulkan_semaphore_binary cuda_interop_import_vulkan_semaphore_binary
#define cuda_p2p_init cuda_interop_init
#define cuda_p2p_register_gl_buffer cuda_interop_register_gl_buffer
#define cuda_p2p_register_gl_image cuda_interop_register_gl_image
#define cuda_p2p_release_buffer cuda_interop_release_buffer
#define cuda_p2p_release_image cuda_interop_release_image
#define cuda_p2p_release_semaphore cuda_interop_release_semaphore
#define CudaP2PResourceHandle CudaInteropResourceHandle
#define CudaP2PResource_t CudaInteropResource_t
#define CudaP2PSemaphoreHandle CudaInteropSemaphoreHandle
#define CudaP2PSemaphore_t CudaInteropSemaphore_t
#define cuda_p2p_shutdown cuda_interop_shutdown
#define CUDA_P2P_SUCCESS CUDA_INTEROP_SUCCESS
#define cuda_p2p_sync cuda_interop_sync
#define cuda_p2p_upload_buffer cuda_interop_upload_buffer
#define cuda_p2p_wait_semaphore cuda_interop_wait_semaphore
