set(CMAKE_BUILD_TYPE Debug CACHE INTERNAL "")
set(SCORE_PCH False)
set(SCORE_STATIC_PLUGINS True)
set(SCORE_DEPLOYMENT_BUILD False)
set(SCORE_AUDIO_PLUGINS True CACHE INTERNAL "")
set(SCORE_COVERAGE True)

include(default-plugins)
