set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE INTERNAL "")
set(SCORE_PCH True)
set(DEPLOYMENT_BUILD True)

set(SCORE_AUDIO_PLUGINS True CACHE INTERNAL "")
include(default-plugins)

set(SCORE_STATIC_PLUGINS True)
