set(CMAKE_BUILD_TYPE Release CACHE INTERNAL "")
set(SCORE_PCH True CACHE INTERNAL "")
set(DEPLOYMENT_BUILD True CACHE INTERNAL "")
set(SCORE_ENABLE_LTO True CACHE INTERNAL "")

include(minimal-plugins)

set(SCORE_STATIC_PLUGINS True CACHE INTERNAL "")
set(SCORE_AUDIO_PLUGINS 0 CACHE INTERNAL "")
set(SCORE_DISABLE_ADDONS 1 CACHE INTERNAL "")

set(SCORE_DISABLE_PROTOCOLS 1 CACHE INTERNAL "")
