#!/usr/bin/env python3
"""Generate smaller versions of the default skin.

Same families, same colours, every font size shifted down by a fixed amount.
The variants are named after the size the application font ends up at, since
that is the one people actually notice: Default is 13 px, so Default12px is
everything minus one and Default11px is everything minus two.

Nothing here is on a pixel grid: Ubuntu and Courier Prime are ordinary outline
fonts, so any integer size renders, and a smaller size is simply smaller
rather than sharper. The floor exists only so the tiny roles stay legible -
medium7 is already 9 px in the default, and 7 px is about where Ubuntu stops
being readable at all.

Run from this directory:  python3 generate-default-variants.py
Then add any new file to ../score.qrc.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# Smallest pixel size we will shrink a role to.
FLOOR = 7

# (file stem, how many pixels to take off every size)
VARIANTS = [
    ("Default12px", 1),
    ("Default11px", 2),
]


def shrink(fonts, by):
    out = {}
    for role, spec in fonts.items():
        if role.startswith("_"):
            continue
        spec = dict(spec)
        if (px := spec.get("pixelSize", 0)) > 0:
            spec["pixelSize"] = max(FLOOR, px - by)
        out[role] = spec
    return out


if __name__ == "__main__":
    with open(os.path.join(HERE, "DefaultSkin.json")) as f:
        default = json.load(f)
    fonts = default["fonts"]

    for stem, by in VARIANTS:
        doc = {k: v for k, v in default.items() if not k.startswith("_") and k != "fonts"}
        shrunk = shrink(fonts, by)
        app = shrunk["application"]["pixelSize"]
        sizes = sorted({s["pixelSize"] for s in shrunk.values() if "pixelSize" in s})
        doc["_comment"] = (
            f"The default skin with every font size reduced by {by} px, so the "
            f"application font is {app} px instead of "
            f"{fonts['application']['pixelSize']} px. Colours and families are "
            f"the default's. Generated by generate-default-variants.py; edit "
            f"DefaultSkin.json and re-run rather than editing this file."
        )
        doc["fonts"] = shrunk
        path = os.path.join(HERE, f"{stem}Skin.json")
        with open(path, "w") as f:
            json.dump(doc, f, indent=1)
            f.write("\n")
        floored = [r for r, s in shrunk.items()
                   if s.get("pixelSize") == FLOOR and fonts[r]["pixelSize"] - by < FLOOR]
        print(
            f"{os.path.basename(path):<24} -{by}px  application {app}px  "
            f"sizes {sizes}" + (f"  (floored: {', '.join(floored)})" if floored else ""))
