import json, sys
res=json.load(open(sys.argv[1]+'/analysis-'+(sys.argv[2] if len(sys.argv)>2 else 'score')+'.json'))
n=len(res)
def c(f): return sum(1 for r in res if f(r))
both=lambda r: r['ref_init'] and r['score_init']
print("modules",n)
print("ref init ok", c(lambda r:r['ref_init']))
print("score init ok", c(lambda r:r['score_init']))
print("ref ok but score init failed", c(lambda r:r['ref_init'] and not r['score_init']))
print("score ok, ref failed", c(lambda r:r['score_init'] and not r['ref_init']))
print("score driver rc!=0", c(lambda r:r['score_rc'] not in (0,None)))
print("action defs mismatch", c(lambda r:both(r) and r['ref_defs'][0]!=r['score_tree'][0]))
print("feedback defs mismatch", c(lambda r:both(r) and r['ref_defs'][1]!=r['score_tree'][1]))
print("variable defs mismatch (tree)", c(lambda r:both(r) and r['ref_defs'][2]!=r['score_tree'][2]))
print("config diffs", c(lambda r:bool(r['config_diffs'])))
print("action option diffs", c(lambda r:bool(r['action_option_diffs'])), sum(len(r['action_option_diffs']) for r in res))
print("actions failing only in score", c(lambda r:bool(r['actions_failing_only_in_score'])), sum(len(r['actions_failing_only_in_score']) for r in res))
print("wire diffs", c(lambda r:bool(r['wire_diffs'])), sum(len(r['wire_diffs']) for r in res))
print("variables value diffs", c(lambda r:bool(r['var_value_diffs'])), sum(len(r['var_value_diffs']) for r in res))
print("feedback values fewer in score", c(lambda r:(r['fb_score_values'] or 0) < (r['fb_ref_values'] or 0)))
print("options w/o param", c(lambda r:bool(r['options_without_param'])), sum(len(r['options_without_param']) for r in res))
print("host unhandled", c(lambda r:bool(r['host_unhandled_calls'])))
print("actions ok ref/score", sum(r['actions_ref_ok'] for r in res), sum(r['actions_score_ok'] for r in res))
