#!/bin/sh
export LD_LIBRARY_PATH="${APPIMAGE_LIBRARY_PATH}:${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"
"${APPDIR}/usr/bin/linuxcheck" "${APPDIR}/usr/bin/ossia-score"
exec "${APPDIR}/usr/bin/ossia-score" "$@"
