#pragma once

// Example only
#define MAIN_QML "$QML"
#define SCORE_FILE "$SCORE"
#define HAS_AUTOPLAY 1
#define HAS_SCORE 1

#define SCORE_CUSTOM_APP_ORGANIZATION_NAME "$SCORE_CUSTOM_APP_ORGANIZATION_NAME"
#define SCORE_CUSTOM_APP_ORGANIZATION_DOMAIN "$SCORE_CUSTOM_APP_ORGANIZATION_DOMAIN"
#define SCORE_CUSTOM_APP_APPLICATION_NAME "$SCORE_CUSTOM_APP_APPLICATION_NAME"
#define SCORE_CUSTOM_APP_APPLICATION_VERSION "$SCORE_CUSTOM_APP_APPLICATION_VERSION"
