if(APPLE)

# Copy the dylibs if necessary
if(NOT ISCORE_STATIC_PLUGINS)
    set(ISCORE_BUNDLE_PLUGINS_FOLDER "${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/")
    function(iscore_copy_osx_plugin theTarget)
        add_custom_command(
          TARGET ${APPNAME} POST_BUILD
          COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:target> ${ISCORE_BUNDLE_PLUGINS_FOLDER})
    endfunction()

    # Copy iscore plugins into the app bundle
    add_custom_command(TARGET ${APPNAME} POST_BUILD
                       COMMAND mkdir -p ${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/)
    iscore_copy_osx_plugin(iscore_plugin_curve)
    iscore_copy_osx_plugin(iscore_plugin_inspector)
    iscore_copy_osx_plugin(iscore_plugin_scenario)
    iscore_copy_osx_plugin(iscore_plugin_pluginsettings)
    iscore_copy_osx_plugin(iscore_plugin_deviceexplorer)

    if(TARGET iscore_plugin_network)
        iscore_copy_osx_plugin(iscore_plugin_network)
    endif()
    if(TARGET iscore_plugin_cohesion)
        iscore_copy_osx_plugin(iscore_plugin_cohesion)
    endif()
    if(TARGET iscore_plugin_ossia)
        iscore_copy_osx_plugin(iscore_plugin_ossia)
    endif()
    # TODO it's not a plugin. It should be copied to the MacOS folder instead.
    # add_custom_command(TARGET ${APPNAME} POST_BUILD
    #                  COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:process_interface> ${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/)
endif()



find_package(Jamoma)
if(${Jamoma_FOUND})
    # Copy the Jamoma files in the bundle generated by the build phase
    copy_in_bundle_jamoma(${APPNAME} ${CMAKE_BINARY_DIR}/${APPNAME}.app "${JAMOMA_LIBS}" "${JAMOMA_PLUGINS}")
endif()

# Remember to set CMAKE_INSTALL_PREFIX on the CMake command line.
# Qt setup
include(DeployQt5)
if(ISCORE_STATIC_PLUGINS) # For now we only take this branch
    foreach(plugin ${ISCORE_PLUGINS})
        list(APPEND ISCORE_BUNDLE_INSTALLED_PLUGINS ${APPNAME}.app/Contents/MacOS/plugins/lib${plugin}.dylib)
    endforeach()

    # We don't put the Jamoma path in here, because the paths get perverted by DeployQt5.
    install_qt5_executable(${APPNAME}.app "" "" "${CMAKE_BINARY_DIR}/base/lib")
else()
    # TODO fix this.
    set(ISCORE_PLUGINS "device_explorer_plugin;inspector_plugin;scenario_process;CurvePlugin;iscore_cohesion;networkplugin;pluginsettings_plugin")

    foreach(plugin ${ISCORE_PLUGINS})
        list(APPEND ISCORE_BUNDLE_INSTALLED_PLUGINS ${APPNAME}.app/Contents/MacOS/plugins/lib${plugin}.dylib)
    endforeach()

    install_qt5_executable(${APPNAME}.app
                           ""
                           "${ISCORE_BUNDLE_INSTALLED_PLUGINS}"
                           "${CMAKE_BINARY_DIR};${CMAKE_BINARY_DIR}/plugins;${CMAKE_BINARY_DIR}/base/lib;${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/")
endif()


if(${Jamoma_FOUND})
    # After installation and fix-up by DeployQt5, we import the Jamoma libraries.
    # They are put in the RPATH.
    fixup_bundle_jamoma(${CMAKE_INSTALL_PREFIX}/${APPNAME}.app ${APPNAME} "${JAMOMA_LIBS}")
endif()

set(CPACK_GENERATOR "DragNDrop")

endif()
