if(APPLE)

set_target_properties(
  ${APPNAME}
  PROPERTIES
    MACOSX_BUNDLE_INFO_STRING "i-score, an interactive sequencer for the intermedia arts"
    MACOSX_BUNDLE_GUI_IDENTIFIER "org.i-score"
    MACOSX_BUNDLE_LONG_VERSION_STRING "${ISCORE_VERSION}"
    MACOSX_BUNDLE_BUNDLE_NAME "i-score"
    MACOSX_BUNDLE_SHORT_VERSION_STRING "${ISCORE_VERSION}"
    MACOSX_BUNDLE_BUNDLE_VERSION "${ISCORE_VERSION}"
    MACOSX_BUNDLE_COPYRIGHT "The i-score team"
    MACOSX_BUNDLE_ICON_FILE "i-score.icns"
    MACOSX_BUNDLE_INFO_PLIST "${CMAKE_CURRENT_SOURCE_DIR}/Info.plist.in"
)

# Copy the dylibs if necessary
if(NOT ISCORE_STATIC_PLUGINS)
    set(ISCORE_BUNDLE_PLUGINS_FOLDER "${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/")
    function(iscore_copy_osx_plugin theTarget)
        add_custom_command(
          TARGET ${APPNAME} POST_BUILD
          COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:target> ${ISCORE_BUNDLE_PLUGINS_FOLDER})
    endfunction()

    # Copy iscore plugins into the app bundle
    add_custom_command(TARGET ${APPNAME} POST_BUILD
                       COMMAND mkdir -p ${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/)

    foreach(plugin ${ISCORE_PLUGINS_LIST})
        iscore_copy_osx_plugin(${plugin})
    endforeach()
endif()



find_package(Jamoma)
if(${Jamoma_FOUND})
    # Copy the Jamoma files in the bundle generated by the build phase
    copy_in_bundle_jamoma(${APPNAME} ${CMAKE_BINARY_DIR}/${APPNAME}.app "${JAMOMA_LIBS}" "${JAMOMA_PLUGINS}")
endif()

# Remember to set CMAKE_INSTALL_PREFIX on the CMake command line.
# Qt setup
include(DeployQt5)
if(ISCORE_STATIC_PLUGINS) # For now we only take this branch
    # We don't put the Jamoma path in here, because the paths get perverted by DeployQt5.
    install_qt5_executable(${APPNAME}.app "" "" "${CMAKE_BINARY_DIR}/base/lib")
else()
    foreach(plugin ${ISCORE_PLUGINS_LIST})
        list(APPEND ISCORE_BUNDLE_INSTALLED_PLUGINS ${APPNAME}.app/Contents/MacOS/plugins/lib${plugin}.dylib)
    endforeach()

    install_qt5_executable(${APPNAME}.app
                           ""
                           "${ISCORE_BUNDLE_INSTALLED_PLUGINS}"
                           "${CMAKE_BINARY_DIR};${CMAKE_BINARY_DIR}/plugins;${CMAKE_BINARY_DIR}/base/lib;${CMAKE_BINARY_DIR}/${APPNAME}.app/Contents/MacOS/plugins/")
endif()

if(${Jamoma_FOUND})
    # After installation and fix-up by DeployQt5, we import the Jamoma libraries.
    # They are put in the RPATH.
    fixup_bundle_jamoma(${CMAKE_INSTALL_PREFIX}/${APPNAME}.app ${APPNAME} "${JAMOMA_LIBS}")
endif()

set(CPACK_GENERATOR "DragNDrop")

endif()
