if(WIN32)
  if(CMAKE_C_COMPILER_ID MATCHES "Clang")
    if(NOT (CMAKE_C_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC"))
      set(SCORE_COMPILER_NEEDS_GCODEVIEW 1)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(SCORE_COMPILER_NEEDS_GCODEVIEW 1)
  endif()

  if (SCORE_COMPILER_NEEDS_GCODEVIEW)
    set(CMAKE_C_FLAGS_Debug_INIT "-g -gcodeview")
    set(CMAKE_CXX_FLAGS_Debug_INIT "-g -gcodeview")
    set(CMAKE_C_FLAGS_RelWithDebInfo_INIT "-O2 -g -DNDEBUG -gcodeview")
    set(CMAKE_CXX_FLAGS_RelWithDebInfo_INIT "-O2 -g -DNDEBUG -gcodeview")
    set(CMAKE_SHARED_LINKER_FLAGS_Debug_INIT "-g -gcodeview -Wl,--pdb=")
    set(CMAKE_SHARED_LINKER_FLAGS_RelWithDebInfo_INIT "-g -gcodeview -Wl,--pdb=")
    set(CMAKE_EXE_LINKER_FLAGS_Debug_INIT "-g -gcodeview -Wl,--pdb=")
    set(CMAKE_EXE_LINKER_FLAGS_RelWithDebInfo_INIT "-g -gcodeview -Wl,--pdb=")
    set(CMAKE_MODULE_LINKER_FLAGS_Debug_INIT "-g -gcodeview -Wl,--pdb=")
    set(CMAKE_MODULE_LINKER_FLAGS_RelWithDebInfo_INIT "-g -gcodeview -Wl,--pdb=")
  endif()
endif()
