if(NOT SCORE_MSSTORE_DEPLOYMENT)
  return()
endif()

install(
  # Generated by ScoreConfiguration.cmake at ${CMAKE_BINARY_DIR}; this file is
  # included from src/app scope where ${PROJECT_BINARY_DIR} differs, so use the
  # top-level binary dir to match where the manifest is actually written.
  FILES
    "${CMAKE_BINARY_DIR}/score.exe.manifest"
  DESTINATION
    "."
)

install(
  DIRECTORY
    "${CMAKE_CURRENT_LIST_DIR}/Deployment/Windows/store/images"
  DESTINATION
    "."
)


configure_file(
  "${CMAKE_CURRENT_LIST_DIR}/Deployment/Windows/store/manifests/Package.appxmanifest.in"
  "${PROJECT_BINARY_DIR}/manifests/Package.appxmanifest"
  )

install(
  FILES
    "${PROJECT_BINARY_DIR}/manifests/Package.appxmanifest"
  DESTINATION
    "manifests/"
)
