#!/bin/bash -eux

# This script will run ossia score as a CLI only version.
# Most features will not be available but it will be more efficient and it will use very little RAM.

DIR=$(realpath "${BASH_SOURCE[0]}")
DIR=$(dirname "$DIR")

source "$DIR/setup-dependencies.sh"

export QT_QPA_PLATFORM=minimal

"$DIR/ossia-score" --no-opengl --no-gui --no-restore $@
