#!/bin/bash -eux

DIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))

export MESA_GLES_VERSION_OVERRIDE=3.2
export MESA_GLSL_VERSION_OVERRIDE=320
export LD_LIBRARY_PATH="$DIR/lib"
export QT_QPA_PLATFORM=eglfs

"$DIR/bin/ossia-score" $@ --no-opengl
