name: AppImage
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  appimage:
    name: AppImage
    strategy:
      matrix:
        include:
          - { image: ubuntu-24.04, cpu_arch: x86_64 }
          - { image: ubuntu-24.04-arm, cpu_arch: aarch64 }

    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        run: |
          export CPU_ARCH=${{ matrix.cpu_arch }}
          ./ci/appimage.deps.sh

      - name: Build
        run: |
          export CPU_ARCH=${{ matrix.cpu_arch }}
          ./ci/appimage.build.sh

      - name: Deploy
        run: |
          export GITTAGNOV=$(echo "$GITHUB_REF" | sed "s/.*\///;s/^v//")
          export BUILD_ARTIFACTSTAGINGDIRECTORY="$PWD/staging"
          export CPU_ARCH=${{ matrix.cpu_arch }}
          mkdir -p "$BUILD_ARTIFACTSTAGINGDIRECTORY"
          ./ci/appimage.deploy.sh

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: appimage-${{ matrix.cpu_arch }}
          path: |
            staging/*.*

      - name: Continuous
        uses: softprops/action-gh-release@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }} && github.event_name != 'pull_request'
        with:
          name: "Continuous"
          tag_name: "continuous"
          body: ""
          append_body: true
          generate_release_notes: false
          files: |
            staging/*.*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
        with:
          body: ""
          append_body: true
          generate_release_notes: false
          files: |
            staging/*.*
