name: BSDs
on: push

jobs:
  build_bsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          echo "==== 1 ===="
          cd work
          find . -name freebsd.deps.sh

          echo "==== 2 ====: $GITHUB_WORKSPACE"
          cd $GITHUB_WORKSPACE
          find . -name freebsd.deps.sh
          ./ci/freebsd.deps.sh

        run: |
          ./ci/freebsd.build.sh
