name: Debian build
on: [push,pull_request]

jobs:
  debian:
    name: Debian
    runs-on: ubuntu-latest
    container:
      image: debian:${{ matrix.distro }}

    strategy:
      matrix:
        include:
          - { distro: bookworm, CC: clang,     CXX: clang++,    PACKAGES: "clang" }
          - { distro: bookworm, CC: clang-15,  CXX: clang++-15, PACKAGES: "clang-15" }
          - { distro: bookworm, CC: gcc,       CXX: g++,        PACKAGES: "build-essential" }
          - { distro: trixie, CC: gcc,         CXX: g++,        PACKAGES: "build-essential  llvm-17-dev libclang-17-dev " }
          - { distro: trixie, CC: clang,       CXX: clang++,    PACKAGES: "clang  llvm-17-dev libclang-17-dev " }
          - { distro: trixie, CC: gcc-14,      CXX: g++-14,     PACKAGES: "gcc-14 g++-14  llvm-17-dev libclang-17-dev " }
          - { distro: trixie, CC: clang-17,    CXX: clang++-17, PACKAGES: "clang-17 llvm-17-dev libclang-17-dev " }
    steps:
      - name: Install git
        run: |
          apt-get update -qq
          apt-get install -qq --force-yes git

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
          PACKAGES: ${{ matrix.packages }}
        run: |
          ./ci/${{ matrix.distro }}.deps.sh

      - name: Build
        env:
          CC: ${{ matrix.CC }}
          CXX: ${{ matrix.CXX }}
        run: |
          ./ci/${{ matrix.distro }}.build.sh
