name: Flatpak
on: [push,pull_request]

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.7
      options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.ossia.score.flatpak
        manifest-path: ./cmake/Deployment/Linux/Flatpak/io.ossia.score.yml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Continuous
      uses: softprops/action-gh-release@v2
      if: github.event_name != 'pull_request'
      with:
        name: "Continuous"
        tag_name: "continuous"
        body: ""
        append_body: true
        generate_release_notes: false
        files: |
          *.flatpak

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
      with:
        body: ""
        append_body: true
        generate_release_notes: false
        files: |
          *.flatpak