name: WASM
on: [push,pull_request]

jobs:
  wasm:
    name: WebAssembly
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install git
        run: |
          pacman -Syy --noconfirm
          pacman -S glibc --noconfirm
          pacman -S git --noconfirm

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          persist-credentials: false
          fetch-depth: 0

      - name: Dependencies
        run: |
          ./ci/wasm.deps.sh

      - name: Build
        run: |
          ./ci/wasm.build.sh

      - name: Deploy
        run: |
          ./ci/wasm.deploy.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.event_name != 'pull_request'
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          branch: 'main'
          force: true
          directory: './site'
          repository: 'ossia/score-web'
