name: Windows build
on: [push,pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  mingw:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: ucrt64,  env: ucrt-x86_64 }
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Dependencies
        shell: bash
        run: |
          ./ci/mingw.deps.sh

      - name: Setup msys2 and mingw-w64
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          pacboy: >-
            cmake:p
            ninja:p
            toolchain:p
            cppwinrt:p
            qt6-base:p
            qt6-declarative:p
            qt6-websockets:p
            qt6-serialport:p
            qt6-shadertools:p
            qt6-scxml:p
            qt6-tools:p
            boost:p
            portaudio:p
            fftw:p
            ffmpeg:p
            SDL2:p

      - name: Build
        shell: msys2 {0}
        run: |
          ./ci/mingw.build.sh

