name: Windows build
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  win32:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Long path support
        run: git config --global core.longpaths true

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: latest
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Dependencies
        shell: bash
        run: ./ci/win32.deps.sh

      - name: Build
        shell: bash
        run: ./ci/win32.build.sh

      - name: Deploy
        shell: bash
        run: |
          export GITTAGNOV=$(echo "$GITHUB_REF" | sed "s/.*\///;s/^v//")
          export BUILD_ARTIFACTSTAGINGDIRECTORY="$PWD/staging"
          mkdir -p "$BUILD_ARTIFACTSTAGINGDIRECTORY"
          ./ci/win32.deploy.sh

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: |
            staging/*.*

      - name: Continuous
        uses: softprops/action-gh-release@v3
        if: github.ref == 'refs/heads/master'
        with:
          name: "Continuous"
          tag_name: "continuous"
          body: ""
          append_body: true
          generate_release_notes: false
          files: |
            staging/*.*

      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ""
          append_body: true
          generate_release_notes: false
          files: |
            staging/*.*
